### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by ola2403** [diogomatoschaves/osm-feature-extractor#21]
Good morning,

Thanks for your work on this code. I have a question: where does the input geojson file come from? I saw you mentioned Kontur website but the 'isle-of-wight.geojson' file is different from the ones that can be found there. If I load the geojson file from Kontur, I get appropiate hexagons but unfortunately all of their features counts equal to 0.

I would really appreciate your explanation :)

**Comment by diogomatoschaves** [comment]
Hi @ola2403, apologies for the delay. The input file should be a `osm.pbf` file, not a `geojson`. Have you tried with that?

**Comment by ola2403** [comment]
I have. I believe there is a need for two input files: osm.pbf and geojson. But I have already worked it out, thanks for your help!
